### ISSUE TITLE
La primera vez se abre, la segunda, no

### ISSUE THREAD

**Issue by aitormendez** [SuperheroesX-Dev/SuperheroesX#10]
![Captura de pantalla 2019-03-08 21 42 15](https://user-images.githubusercontent.com/2788577/54055417-4d36c380-41ed-11e9-86ae-d5bc28927512.png)

Dejo el log:
[latest.log](https://github.com/SuperheroesX-Dev/SuperheroesX/files/2947418/latest.log)

MC 1.13.2 con Forge para 1.13.2

Java 8 actualización 201

**Comment by Minecraftschurli** [comment]
Try re downloading the newest version and use it with the latest forge

**Comment by aitormendez** [comment]
SuperheroesX-1.13.2-0.4.1.jar (i think it is the latest)
forge-1.13.2-25.0.74

The error persist.

**Comment by Minecraftschurli** [comment]
delete the config file

**Comment by aitormendez** [comment]
Perfect! It works. Thank you for the help.
